/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String baby = "assets/meal_images/baby.png";
  static const String baby_food = "assets/meal_images/baby_food.jpg";
  static const String can1 = "assets/meal_images/can1.jpg";
  static const String can2 = "assets/meal_images/can2.png";
  static const String candy = "assets/meal_images/candy.png";
  static const String candy1 = "assets/meal_images/candy1.png";
  static const String chips = "assets/meal_images/chips.jpg";
  static const String chips1 = "assets/meal_images/chips1.png";
  static const String fanta = "assets/meal_images/fanta.png";
  static const String food = "assets/meal_images/food.png";
  static const String green_tea = "assets/meal_images/green-tea.png";
  static const String img = "assets/img.png";
  static const String img_1 = "assets/img_1.png";
  static const String img_2 = "assets/img_2.png";
  static const String layes = "assets/meal_images/layes.png";
  static const String meal = "assets/meal_images/meal.png";
  static const String milka = "assets/meal_images/milka.png";
  static const String pepsii = "assets/meal_images/pepsii.png";
  static const String ritter = "assets/meal_images/ritter.jpg";
  static const String scolate = "assets/meal_images/scolate.png";
  static const String scolates = "assets/meal_images/scolates.png";
  static const String seven = "assets/meal_images/seven.png";
  static const String soda = "assets/meal_images/soda.jpg";
  static const String sweets = "assets/meal_images/sweets.jpg";
  static const String syrup = "assets/meal_images/syrup.jpg";
  static const String tea = "assets/meal_images/tea.png";
  static const String tea_coffee = "assets/meal_images/tea_coffee.png";
}
