/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String img = "assets/pepsii.png";
  static const String img_1 = "assets/img_1.png";
  static const String img_2 = "assets/img_2.png";
}
